vcpkg_check_linkage(ONLY_STATIC_LIBRARY)

vcpkg_from_git(
    OUT_SOURCE_PATH SOURCE_PATH
    URL https://github.com/microsoft/cpp_client_telemetry.git
    REF 88defca71f0f0afe406a892b32e61e0cf6d915fe
    FETCH_REF v${VERSION}
    HEAD_REF main
)

set(MATSDK_BUILD_APPLE_HTTP OFF)
if(VCPKG_TARGET_IS_OSX OR VCPKG_TARGET_IS_IOS)
    set(MATSDK_BUILD_APPLE_HTTP ON)
endif()

if("minimal-sqlite" IN_LIST FEATURES AND "system-sqlite" IN_LIST FEATURES)
    message(FATAL_ERROR "cpp-client-telemetry features minimal-sqlite and system-sqlite are mutually exclusive")
endif()

set(MATSDK_SQLITE_PROVIDER SYSTEM)
if("minimal-sqlite" IN_LIST FEATURES)
    set(MATSDK_SQLITE_PROVIDER MINIMAL)
endif()

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DMATSDK_BUILD_HEADERS=ON
        -DMATSDK_BUILD_LIBRARY=ON
        -DMATSDK_BUILD_TEST_TOOL=OFF
        -DMATSDK_BUILD_UNIT_TESTS=OFF
        -DMATSDK_BUILD_FUNC_TESTS=OFF
        -DMATSDK_BUILD_PRIVACYGUARD=OFF
        -DMATSDK_BUILD_CDS=OFF
        -DMATSDK_BUILD_LIVEEVENTINSPECTOR=OFF
        -DMATSDK_BUILD_SIGNALS=OFF
        -DMATSDK_BUILD_SANITIZER=OFF
        -DMATSDK_BUILD_AZMON=OFF
        -DMATSDK_BUILD_JNI_WRAPPER=OFF
        -DMATSDK_BUILD_OBJC_WRAPPER=OFF
        -DMATSDK_BUILD_SWIFT_WRAPPER=OFF
        -DMATSDK_BUILD_PACKAGE=OFF
        -DMATSDK_DISABLE_LOGGING=ON
        -DBUILD_VERSION=${VERSION}
        -DMATSDK_BUILD_APPLE_HTTP=${MATSDK_BUILD_APPLE_HTTP}
        -DMATSDK_ANDROID_HTTP_CLIENT=CURL
        -DMATSDK_CURL_PROVIDER=SYSTEM
        -DMATSDK_SQLITE_PROVIDER=${MATSDK_SQLITE_PROVIDER}
        -DMATSDK_ZLIB_PROVIDER=SYSTEM
)

vcpkg_cmake_install()
vcpkg_cmake_config_fixup(PACKAGE_NAME MSTelemetry CONFIG_PATH lib/cmake/MSTelemetry)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
