# <complete_code>
# <imports>
import json

from foundry_local_sdk import (
    ChatSession,
    Configuration,
    FoundryLocalManager,
    MessageItem,
    Request,
    RequestOptions,
    TextItem,
    ToolCallItem,
    ToolChoice,
    ToolResultItem,
)
# </imports>


# <tool_definitions>
def multiply_numbers(first: int, second: int) -> int:
    return first * second


MULTIPLY_NUMBERS_SCHEMA = json.dumps({
    "type": "object",
    "properties": {
        "first": {"type": "integer", "description": "The first number in the operation"},
        "second": {"type": "integer", "description": "The second number in the operation"},
    },
    "required": ["first", "second"],
})
# </tool_definitions>


def main():
    # <init>
    config = Configuration(app_name="foundry_local_samples")
    FoundryLocalManager.initialize(config)
    manager = FoundryLocalManager.instance

    current_ep = ""

    def ep_progress(ep_name: str, percent: float):
        nonlocal current_ep
        if ep_name != current_ep:
            if current_ep:
                print()
            current_ep = ep_name
        print(f"\r  {ep_name:<30}  {percent:5.1f}%", end="", flush=True)

    manager.download_and_register_eps(progress_callback=ep_progress)
    if current_ep:
        print()
    # </init>

    # <model_setup>
    model = manager.catalog.get_model("qwen2.5-0.5b")
    model.download(
        lambda progress: print(
            f"\rDownloading model: {progress:.2f}%",
            end="",
            flush=True,
        )
    )
    print()
    model.load()
    print("Model loaded and ready.")
    # </model_setup>

    # <tool_loop>
    # Register the tool definition on the session. The model sees it on every turn.
    with ChatSession(model) as session:
        session.add_tool_definition(
            "multiply_numbers",
            "A tool for multiplying two numbers.",
            MULTIPLY_NUMBERS_SCHEMA,
        )

        # Turn 1: force a tool call so we can demonstrate the round-trip.
        # ChatSession accumulates message history, so we only add new items each turn.
        with Request() as req1:
            req1.add_item(MessageItem.system(
                "You are a helpful AI assistant. If necessary, you can use any provided tools to answer the question."
            ))
            req1.add_item(MessageItem.user("What is the answer to 7 multiplied by 6?"))
            req1.set_options(RequestOptions(tool_choice=ToolChoice.REQUIRED))

            print("\nChat completion response:")
            response = session.process_request(req1)

            # Collect tool calls, invoke them, and stage the tool-result items for turn 2.
            pending_results: list[ToolResultItem] = []
            for item in response:
                if isinstance(item, ToolCallItem) and item.name == "multiply_numbers":
                    args = json.loads(item.arguments)
                    first, second = args["first"], args["second"]
                    print(f"\nInvoking tool: {item.name} with arguments {first} and {second}")
                    result = multiply_numbers(first, second)
                    print(f"Tool response: {result}")
                    pending_results.append(ToolResultItem(item.call_id, str(result)))

        print("\nTool calls completed. Prompting model to continue conversation...\n")

        # Turn 2: send the tool results back. ToolChoice defaults to AUTO.
        session.set_streaming(True)
        with Request() as req2:
            for tool_result in pending_results:
                req2.add_item(tool_result)
            req2.add_item(MessageItem.system("Respond only with the answer generated by the tool."))

            print("Chat completion response:")
            for item in session.process_streaming_request(req2):
                if isinstance(item, TextItem):
                    print(item.text, end="", flush=True)
            print()
    # </tool_loop>

    # <cleanup>
    model.unload()
    print("Model unloaded.")
    # </cleanup>


if __name__ == "__main__":
    main()
# </complete_code>
