// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
#pragma once

#include <cstddef>

namespace fl {

/// Embedded catalog snapshot bytes. Generated by the catalog_snapshot tool;
/// the .cc file is checked in, and this header simply exposes the symbols.
extern const unsigned char kCatalogSnapshotJson[];
extern const std::size_t kCatalogSnapshotJsonSize;

}  // namespace fl
