// --------------------------------------------------------------------------------------------------------------------
// <copyright company="Microsoft">
//   Copyright (c) Microsoft. All rights reserved.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

namespace Microsoft.AI.Foundry.Local.OpenAI;

using System.Collections.Generic;
using System.Text.Json.Serialization;

/// <summary>
/// Role of a chat message author.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<ChatMessageRole>))]
public enum ChatMessageRole
{
    /// <summary>System instruction message.</summary>
    [JsonStringEnumMemberName("system")]
    System,

    /// <summary>User input message.</summary>
    [JsonStringEnumMemberName("user")]
    User,

    /// <summary>Assistant response message.</summary>
    [JsonStringEnumMemberName("assistant")]
    Assistant,

    /// <summary>Tool result message.</summary>
    [JsonStringEnumMemberName("tool")]
    Tool
}

/// <summary>
/// Type of tool call or tool definition.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<ToolType>))]
public enum ToolType
{
    /// <summary>A function tool.</summary>
    [JsonStringEnumMemberName("function")]
    Function
}

/// <summary>
/// Represents a chat message in a conversation.
/// </summary>
public class ChatMessage
{
    /// <summary>The role of the message author.</summary>
    [JsonPropertyName("role")]
    public ChatMessageRole Role { get; set; }

    /// <summary>The text content of the message.</summary>
    [JsonPropertyName("content")]
    public string? Content { get; set; }

    /// <summary>Optional name of the author of the message.</summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <summary>Tool call ID this message is responding to.</summary>
    [JsonPropertyName("tool_call_id")]
    public string? ToolCallId { get; set; }

    /// <summary>Tool calls generated by the model.</summary>
    [JsonPropertyName("tool_calls")]
    public IList<ToolCall>? ToolCalls { get; set; }

    /// <summary>Deprecated function call generated by the model.</summary>
    [JsonPropertyName("function_call")]
    public FunctionCall? FunctionCall { get; set; }
}

/// <summary>
/// Represents a tool call generated by the model.
/// </summary>
public class ToolCall
{
    /// <summary>The index of this tool call in the list.</summary>
    [JsonPropertyName("index")]
    public int Index { get; set; }

    /// <summary>The unique ID of the tool call.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>The type of tool call.</summary>
    [JsonPropertyName("type")]
    public ToolType Type { get; set; }

    /// <summary>The function that the model called.</summary>
    [JsonPropertyName("function")]
    public FunctionCall? FunctionCall { get; set; }
}

/// <summary>
/// Represents a function call with name and arguments.
/// </summary>
public class FunctionCall
{
    /// <summary>The name of the function to call.</summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <summary>The arguments to pass to the function, as a JSON string.</summary>
    [JsonPropertyName("arguments")]
    public string? Arguments { get; set; }
}
