// --------------------------------------------------------------------------------------------------------------------
// <copyright company="Microsoft">
//   Copyright (c) Microsoft. All rights reserved.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

namespace Microsoft.AI.Foundry.Local.OpenAI;

using System.Collections.Generic;
using System.Text.Json.Serialization;

/// <summary>
/// Response from a chat completion request.
/// </summary>
public class ChatCompletionResponse
{
    /// <summary>A unique identifier for the completion.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>The object type (e.g. "chat.completion").</summary>
    [JsonPropertyName("object")]
    public string? ObjectType { get; set; }

    /// <summary>The Unix timestamp when the completion was created.</summary>
    [JsonPropertyName("created")]
    public long CreatedAtUnix { get; set; }

    /// <summary>The model used for the completion.</summary>
    [JsonPropertyName("model")]
    public string? Model { get; set; }

    /// <summary>The list of completion choices.</summary>
    [JsonPropertyName("choices")]
    public List<ChatChoice>? Choices { get; set; }

    /// <summary>Token usage statistics for the request.</summary>
    [JsonPropertyName("usage")]
    public CompletionUsage? Usage { get; set; }

    /// <summary>A fingerprint representing the backend configuration.</summary>
    [JsonPropertyName("system_fingerprint")]
    public string? SystemFingerprint { get; set; }

    /// <summary>Error information, if the request failed.</summary>
    [JsonPropertyName("error")]
    public ResponseError? Error { get; set; }
}

/// <summary>
/// A single completion choice in a chat completion response.
/// </summary>
public class ChatChoice
{
    /// <summary>The index of this choice.</summary>
    [JsonPropertyName("index")]
    public int Index { get; set; }

    /// <summary>The chat message generated by the model (non-streaming).</summary>
    [JsonPropertyName("message")]
    public ChatMessage? Message { get; set; }

    /// <summary>The delta content for streaming responses.</summary>
    [JsonPropertyName("delta")]
    public ChatMessage? Delta { get; set; }

    /// <summary>The reason the model stopped generating (e.g. "stop", "length", "tool_calls", "content_filter").</summary>
    [JsonPropertyName("finish_reason")]
    public string? FinishReason { get; set; }
}

/// <summary>
/// Token usage statistics for a completion request.
/// </summary>
public class CompletionUsage
{
    /// <summary>Number of tokens in the prompt.</summary>
    [JsonPropertyName("prompt_tokens")]
    public int PromptTokens { get; set; }

    /// <summary>Number of tokens in the completion.</summary>
    [JsonPropertyName("completion_tokens")]
    public int? CompletionTokens { get; set; }

    /// <summary>Total number of tokens used.</summary>
    [JsonPropertyName("total_tokens")]
    public int TotalTokens { get; set; }
}

/// <summary>
/// Error information returned by the API.
/// </summary>
public class ResponseError
{
    /// <summary>The error code.</summary>
    [JsonPropertyName("code")]
    public string? Code { get; set; }

    /// <summary>A human-readable error message.</summary>
    [JsonPropertyName("message")]
    public string? Message { get; set; }

    /// <summary>The error type (e.g. "invalid_request_error", "server_error").</summary>
    [JsonPropertyName("type")]
    public string? Type { get; set; }

    /// <summary>The parameter that caused the error.</summary>
    [JsonPropertyName("param")]
    public string? Param { get; set; }
}
