// --------------------------------------------------------------------------------------------------------------------
// <copyright company="Microsoft">
//   Copyright (c) Microsoft. All rights reserved.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

namespace Microsoft.AI.Foundry.Local.OpenAI.Responses;

using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;

// =====================================================================================================================
// Enums
// =====================================================================================================================

/// <summary>The status of a Response object lifecycle.</summary>
[JsonConverter(typeof(JsonStringEnumConverter<ResponseStatus>))]
public enum ResponseStatus
{
    [JsonStringEnumMemberName("queued")] Queued,
    [JsonStringEnumMemberName("in_progress")] InProgress,
    [JsonStringEnumMemberName("completed")] Completed,
    [JsonStringEnumMemberName("failed")] Failed,
    [JsonStringEnumMemberName("incomplete")] Incomplete,
    [JsonStringEnumMemberName("cancelled")] Cancelled,
}

/// <summary>The status of an item within a Response.</summary>
[JsonConverter(typeof(JsonStringEnumConverter<ResponseItemStatus>))]
public enum ResponseItemStatus
{
    [JsonStringEnumMemberName("in_progress")] InProgress,
    [JsonStringEnumMemberName("completed")] Completed,
    [JsonStringEnumMemberName("incomplete")] Incomplete,
}

/// <summary>The role of a message in a conversation.</summary>
[JsonConverter(typeof(JsonStringEnumConverter<MessageRole>))]
public enum MessageRole
{
    [JsonStringEnumMemberName("system")] System,
    [JsonStringEnumMemberName("user")] User,
    [JsonStringEnumMemberName("assistant")] Assistant,
    [JsonStringEnumMemberName("developer")] Developer,
    [JsonStringEnumMemberName("tool")] Tool,
    [JsonStringEnumMemberName("tool_response")] ToolResponse,
}

/// <summary>Controls whether the model may call tools.</summary>
[JsonConverter(typeof(JsonStringEnumConverter<ToolChoiceValue>))]
public enum ToolChoiceValue
{
    [JsonStringEnumMemberName("auto")] Auto,
    [JsonStringEnumMemberName("none")] None,
    [JsonStringEnumMemberName("required")] Required,
}

/// <summary>Controls truncation behavior when context exceeds limits.</summary>
[JsonConverter(typeof(JsonStringEnumConverter<TruncationValue>))]
public enum TruncationValue
{
    [JsonStringEnumMemberName("auto")] Auto,
    [JsonStringEnumMemberName("disabled")] Disabled,
}

// =====================================================================================================================
// Content Parts (polymorphic)
// =====================================================================================================================

/// <summary>Base class for all content parts within items.</summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(InputTextContent), "input_text")]
[JsonDerivedType(typeof(OutputTextContent), "output_text")]
[JsonDerivedType(typeof(RefusalContent), "refusal")]
[JsonDerivedType(typeof(InputImageContent), "input_image")]
[JsonDerivedType(typeof(InputFileContent), "input_file")]
public abstract class ContentPart
{
    /// <summary>The type discriminator for the content part.</summary>
    [JsonIgnore]
    public abstract string Kind { get; }
}

/// <summary>Interface for content parts that carry text.</summary>
public interface ITextContent
{
    /// <summary>The text content.</summary>
    string Text { get; }
}

/// <summary>Text content provided as input.</summary>
public sealed class InputTextContent : ContentPart, ITextContent
{
    /// <inheritdoc/>
    [JsonIgnore]
    public override string Kind => "input_text";

    [JsonPropertyName("text")]
    public required string Text { get; set; }
}

/// <summary>Text content generated by the model.</summary>
public sealed class OutputTextContent : ContentPart, ITextContent
{
    /// <inheritdoc/>
    [JsonIgnore]
    public override string Kind => "output_text";

    [JsonPropertyName("text")]
    public required string Text { get; set; }

    [JsonPropertyName("annotations")]
    public List<Annotation> Annotations { get; set; } = [];

    [JsonPropertyName("logprobs")]
    public List<LogProb> Logprobs { get; set; } = [];
}

/// <summary>Content when the model refuses to respond.</summary>
public sealed class RefusalContent : ContentPart
{
    /// <inheritdoc/>
    [JsonIgnore]
    public override string Kind => "refusal";

    [JsonPropertyName("refusal")]
    public required string Refusal { get; set; }
}

/// <summary>Image content provided as input.</summary>
public sealed class InputImageContent : ContentPart
{
    /// <inheritdoc/>
    [JsonIgnore]
    public override string Kind => "input_image";

    /// <summary>Public URL of an image.</summary>
    [JsonPropertyName("image_url")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ImageUrl { get; set; }

    /// <summary>Base64-encoded image data.</summary>
    [JsonPropertyName("image_data")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ImageData { get; set; }

    /// <summary>MIME type of the image (e.g., <c>image/png</c>, <c>image/jpeg</c>). Optional — the server will
    /// infer the type from the data when omitted.</summary>
    [JsonPropertyName("media_type")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? MediaType { get; set; }

    /// <summary>Detail level for image processing: "low", "high", or "auto".</summary>
    [JsonPropertyName("detail")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Detail { get; set; }

    /// <summary>Validates that exactly one of <see cref="ImageUrl"/> or <see cref="ImageData"/> is set.
    /// Called by the client before serialization to surface caller errors close to the call site rather than
    /// returning a server-side 4xx. The factory methods (<see cref="FromFile"/>, <see cref="FromUrl"/>,
    /// <see cref="FromBytes"/>) already produce valid instances; this guards against direct property mutation.</summary>
    /// <exception cref="InvalidOperationException">If both or neither of <see cref="ImageUrl"/> / <see cref="ImageData"/> are set.</exception>
    public void Validate()
    {
        var hasUrl = !string.IsNullOrEmpty(ImageUrl);
        var hasData = !string.IsNullOrEmpty(ImageData);
        if (hasUrl == hasData)
        {
            throw new InvalidOperationException(
                "InputImageContent requires exactly one of ImageUrl or ImageData to be set.");
        }
    }

    /// <summary>Load an image from a local file; base64 encode and detect media type from extension.</summary>
    /// <exception cref="ArgumentException">If <paramref name="path"/> is null/empty.</exception>
    /// <exception cref="FileNotFoundException">If the file does not exist at <paramref name="path"/>.</exception>
    public static InputImageContent FromFile(string path, string? detail = null)
    {
        if (string.IsNullOrWhiteSpace(path))
        {
            throw new ArgumentException("path must be non-empty.", nameof(path));
        }

        if (!File.Exists(path))
        {
            throw new FileNotFoundException($"Image file not found: {path}", path);
        }

        var bytes = File.ReadAllBytes(path);
        var mediaType = DetectMediaType(path);
        return FromBytes(bytes, mediaType, detail);
    }

    /// <summary>Create an image content referencing a URL. <paramref name="mediaType"/> is optional;
    /// when null the server will infer it.</summary>
    public static InputImageContent FromUrl(string url, string? detail = null, string? mediaType = null)
    {
        if (string.IsNullOrWhiteSpace(url))
        {
            throw new ArgumentException("url must be non-empty.", nameof(url));
        }

        return new InputImageContent
        {
            ImageUrl = url,
            MediaType = mediaType,
            Detail = detail,
        };
    }

    /// <summary>Create an image content from raw bytes. <paramref name="mediaType"/> is optional;
    /// when null the server will infer it from the data.</summary>
    public static InputImageContent FromBytes(byte[] data, string? mediaType = null, string? detail = null)
    {
        if (data == null || data.Length == 0)
        {
            throw new ArgumentException("data must be non-empty.", nameof(data));
        }

        return new InputImageContent
        {
            ImageData = Convert.ToBase64String(data),
            MediaType = mediaType,
            Detail = detail,
        };
    }

    private static string? DetectMediaType(string path)
    {
        var ext = Path.GetExtension(path).ToLowerInvariant();
        return ext switch
        {
            ".png" => "image/png",
            ".jpg" or ".jpeg" => "image/jpeg",
            ".gif" => "image/gif",
            ".webp" => "image/webp",
            ".bmp" => "image/bmp",
            _ => null,
        };
    }
}

/// <summary>File content provided as input.</summary>
public sealed class InputFileContent : ContentPart
{
    /// <inheritdoc/>
    [JsonIgnore]
    public override string Kind => "input_file";

    [JsonPropertyName("filename")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Filename { get; set; }

    [JsonPropertyName("file_url")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? FileUrl { get; set; }
}

// =====================================================================================================================
// Annotations and LogProbs
// =====================================================================================================================

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(UrlCitationAnnotation), "url_citation")]
public class Annotation
{
    [JsonIgnore]
    public virtual string Kind { get; set; } = "annotation";

    [JsonPropertyName("start_index")]
    public int StartIndex { get; set; }

    [JsonPropertyName("end_index")]
    public int EndIndex { get; set; }
}

public sealed class UrlCitationAnnotation : Annotation
{
    [JsonIgnore]
    public override string Kind => "url_citation";

    [JsonPropertyName("url")]
    public required string Url { get; set; }

    [JsonPropertyName("title")]
    public required string Title { get; set; }
}

public class LogProb
{
    [JsonPropertyName("token")]
    public required string Token { get; set; }

    [JsonPropertyName("logprob")]
    public double Logprob { get; set; }

    [JsonPropertyName("bytes")]
    public List<int> Bytes { get; set; } = [];

    [JsonPropertyName("top_logprobs")]
    public List<TopLogProb> TopLogprobs { get; set; } = [];
}

public class TopLogProb
{
    [JsonPropertyName("token")]
    public required string Token { get; set; }

    [JsonPropertyName("logprob")]
    public double Logprob { get; set; }

    [JsonPropertyName("bytes")]
    public List<int> Bytes { get; set; } = [];
}

// =====================================================================================================================
// MessageContent union (string | ContentPart[])
// =====================================================================================================================

/// <summary>
/// Represents message content — either a simple string or an array of content parts.
/// Use implicit conversions or factory methods for convenience.
/// </summary>
[JsonConverter(typeof(MessageContentConverter))]
public class MessageContent
{
    /// <summary>The text content if this is a simple string message.</summary>
    public string? Text { get; set; }

    /// <summary>The content parts if this is a structured multimodal message.</summary>
    public List<ContentPart>? Parts { get; set; }

    public static implicit operator MessageContent(string text) => new() { Text = text };

    public static implicit operator MessageContent(List<ContentPart> parts) => new() { Parts = parts };

    public static MessageContent FromText(string text) => new() { Text = text };

    public static MessageContent FromParts(params ContentPart[] parts) => new() { Parts = [.. parts] };

    /// <summary>Get the concatenated text representation.</summary>
    public string GetText()
    {
        if (Text != null)
        {
            return Text;
        }

        if (Parts == null)
        {
            return string.Empty;
        }

        var sb = new System.Text.StringBuilder();
        foreach (var part in Parts)
        {
            if (part is ITextContent t)
            {
                sb.Append(t.Text);
            }
        }

        return sb.ToString();
    }
}

/// <summary>JSON converter for <see cref="MessageContent"/> supporting string or array form.</summary>
public class MessageContentConverter : JsonConverter<MessageContent>
{
    public override MessageContent? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType == JsonTokenType.String)
        {
            return new MessageContent { Text = reader.GetString() };
        }

        if (reader.TokenType == JsonTokenType.StartArray)
        {
            var parts = new List<ContentPart>();
            while (reader.Read() && reader.TokenType != JsonTokenType.EndArray)
            {
                parts.Add(ReadContentPart(ref reader));
            }

            return new MessageContent { Parts = parts };
        }

        if (reader.TokenType == JsonTokenType.Null)
        {
            return null;
        }

        throw new JsonException("MessageContent must be a string or array.");
    }

    private static ContentPart ReadContentPart(ref Utf8JsonReader reader)
    {
        if (reader.TokenType != JsonTokenType.StartObject)
        {
            throw new JsonException($"Expected ContentPart object, found {reader.TokenType}.");
        }

        using var doc = JsonDocument.ParseValue(ref reader);
        var root = doc.RootElement;
        if (!root.TryGetProperty("type", out var typeEl))
        {
            throw new JsonException("ContentPart must have a 'type' property.");
        }

        var type = typeEl.GetString();
        var json = root.GetRawText();
        var ctx = ResponsesSerializationContext.Default;

        ContentPart? result = type switch
        {
            "input_text" => JsonSerializer.Deserialize(json, ctx.InputTextContent),
            "output_text" => JsonSerializer.Deserialize(json, ctx.OutputTextContent),
            "refusal" => JsonSerializer.Deserialize(json, ctx.RefusalContent),
            "input_image" => JsonSerializer.Deserialize(json, ctx.InputImageContent),
            "input_file" => JsonSerializer.Deserialize(json, ctx.InputFileContent),
            _ => throw new JsonException($"Unsupported content part type: '{type}'."),
        };

        return result ?? throw new JsonException($"Failed to deserialize content part of type '{type}'.");
    }

    public override void Write(Utf8JsonWriter writer, MessageContent value, JsonSerializerOptions options)
    {
        if (value.Text != null)
        {
            writer.WriteStringValue(value.Text);
        }
        else if (value.Parts != null)
        {
            writer.WriteStartArray();
            foreach (var part in value.Parts)
            {
                JsonSerializer.Serialize(writer, part, ResponsesSerializationContext.Default.ContentPart);
            }

            writer.WriteEndArray();
        }
        else
        {
            writer.WriteStringValue(string.Empty);
        }
    }
}

// =====================================================================================================================
// Response Items (polymorphic)
// =====================================================================================================================

/// <summary>Base class for items in input/output arrays.</summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(MessageItem), "message")]
[JsonDerivedType(typeof(FunctionCallItem), "function_call")]
[JsonDerivedType(typeof(FunctionCallOutputItem), "function_call_output")]
[JsonDerivedType(typeof(ReasoningItem), "reasoning")]
[JsonDerivedType(typeof(ItemReference), "item_reference")]
public abstract class ResponseItem
{
    /// <summary>The type discriminator for the item (client-side constant).</summary>
    [JsonIgnore]
    public abstract string Kind { get; }

    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Id { get; set; }

    [JsonPropertyName("status")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ResponseItemStatus? Status { get; set; }
}

public sealed class MessageItem : ResponseItem
{
    [JsonIgnore]
    public override string Kind => "message";

    [JsonPropertyName("role")]
    public required MessageRole Role { get; set; }

    [JsonPropertyName("content")]
    public required MessageContent Content { get; set; }
}

public sealed class FunctionCallItem : ResponseItem
{
    [JsonIgnore]
    public override string Kind => "function_call";

    [JsonPropertyName("call_id")]
    public required string CallId { get; set; }

    [JsonPropertyName("name")]
    public required string Name { get; set; }

    [JsonPropertyName("arguments")]
    public required string Arguments { get; set; }
}

public sealed class FunctionCallOutputItem : ResponseItem
{
    [JsonIgnore]
    public override string Kind => "function_call_output";

    [JsonPropertyName("call_id")]
    public required string CallId { get; set; }

    [JsonPropertyName("output")]
    public required MessageContent Output { get; set; }
}

public sealed class ReasoningItem : ResponseItem
{
    [JsonIgnore]
    public override string Kind => "reasoning";

    [JsonPropertyName("content")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<ContentPart>? Content { get; set; }

    [JsonPropertyName("encrypted_content")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? EncryptedContent { get; set; }

    [JsonPropertyName("summary")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Summary { get; set; }
}

public sealed class ItemReference : ResponseItem
{
    [JsonIgnore]
    public override string Kind => "item_reference";

    [JsonPropertyName("item_id")]
    public required string ItemId { get; set; }
}

// =====================================================================================================================
// ResponseInput union (string | ResponseItem[])
// =====================================================================================================================

/// <summary>
/// Represents the input field of a Response create request.
/// Supports either a simple string or an array of structured items.
/// </summary>
[JsonConverter(typeof(ResponseInputConverter))]
public class ResponseInput
{
    public string? Text { get; set; }

    public List<ResponseItem>? Items { get; set; }

    public static implicit operator ResponseInput(string text) => new() { Text = text };

    public static implicit operator ResponseInput(List<ResponseItem> items) => new() { Items = items };
}

public class ResponseInputConverter : JsonConverter<ResponseInput>
{
    public override ResponseInput? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType == JsonTokenType.String)
        {
            return new ResponseInput { Text = reader.GetString() };
        }

        if (reader.TokenType == JsonTokenType.StartArray)
        {
            var items = new List<ResponseItem>();
            while (reader.Read() && reader.TokenType != JsonTokenType.EndArray)
            {
                var item = ReadResponseItem(ref reader);
                if (item != null)
                {
                    items.Add(item);
                }
            }

            return new ResponseInput { Items = items };
        }

        if (reader.TokenType == JsonTokenType.Null)
        {
            return null;
        }

        throw new JsonException("Input must be a string or array of items.");
    }

    private static ResponseItem? ReadResponseItem(ref Utf8JsonReader reader)
    {
        if (reader.TokenType != JsonTokenType.StartObject)
        {
            reader.Skip();
            return null;
        }

        using var doc = JsonDocument.ParseValue(ref reader);
        var root = doc.RootElement;
        if (!root.TryGetProperty("type", out var typeEl))
        {
            return null;
        }

        var type = typeEl.GetString();
        var json = root.GetRawText();
        var ctx = ResponsesSerializationContext.Default;

        return type switch
        {
            "message" => JsonSerializer.Deserialize(json, ctx.MessageItem),
            "function_call" => JsonSerializer.Deserialize(json, ctx.FunctionCallItem),
            "function_call_output" => JsonSerializer.Deserialize(json, ctx.FunctionCallOutputItem),
            "reasoning" => JsonSerializer.Deserialize(json, ctx.ReasoningItem),
            "item_reference" => JsonSerializer.Deserialize(json, ctx.ItemReference),
            _ => null,
        };
    }

    public override void Write(Utf8JsonWriter writer, ResponseInput value, JsonSerializerOptions options)
    {
        if (value.Text != null)
        {
            writer.WriteStringValue(value.Text);
        }
        else if (value.Items != null)
        {
            var ctx = ResponsesSerializationContext.Default;
            writer.WriteStartArray();
            foreach (var item in value.Items)
            {
                JsonSerializer.Serialize(writer, item, ctx.ResponseItem);
            }

            writer.WriteEndArray();
        }
        else
        {
            writer.WriteNullValue();
        }
    }
}

// =====================================================================================================================
// Tool Definition & Tool Choice
// =====================================================================================================================

/// <summary>A function tool definition.</summary>
public class FunctionToolDefinition
{
    [JsonPropertyName("type")]
    public string Type => "function";

    [JsonPropertyName("name")]
    public required string Name { get; set; }

    [JsonPropertyName("description")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Description { get; set; }

    [JsonPropertyName("parameters")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? Parameters { get; set; }

    [JsonPropertyName("strict")]
    public bool Strict { get; set; }
}

public class SpecificToolChoice
{
    [JsonPropertyName("type")]
    public string Type => "function";

    [JsonPropertyName("name")]
    public required string Name { get; set; }
}

/// <summary>Tool choice — either a known string value or a specific function.</summary>
[JsonConverter(typeof(ToolChoiceConverter))]
public class ToolChoice
{
    public ToolChoiceValue? Value { get; set; }

    public SpecificToolChoice? Specific { get; set; }

    public static implicit operator ToolChoice(ToolChoiceValue value) => new() { Value = value };

    public static ToolChoice ForFunction(string name) => new() { Specific = new SpecificToolChoice { Name = name } };
}

public class ToolChoiceConverter : JsonConverter<ToolChoice>
{
    public override ToolChoice? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType == JsonTokenType.String)
        {
            var str = reader.GetString();
            return str switch
            {
                "auto" => new ToolChoice { Value = ToolChoiceValue.Auto },
                "none" => new ToolChoice { Value = ToolChoiceValue.None },
                "required" => new ToolChoice { Value = ToolChoiceValue.Required },
                _ => throw new JsonException($"Unknown tool_choice value: {str}"),
            };
        }

        if (reader.TokenType == JsonTokenType.StartObject)
        {
            using var doc = JsonDocument.ParseValue(ref reader);
            var json = doc.RootElement.GetRawText();
            var specific = JsonSerializer.Deserialize(json, ResponsesSerializationContext.Default.SpecificToolChoice);
            return new ToolChoice { Specific = specific };
        }

        if (reader.TokenType == JsonTokenType.Null)
        {
            return null;
        }

        throw new JsonException("tool_choice must be a string or object.");
    }

    public override void Write(Utf8JsonWriter writer, ToolChoice value, JsonSerializerOptions options)
    {
        if (value.Value.HasValue)
        {
            var str = value.Value.Value switch
            {
                ToolChoiceValue.Auto => "auto",
                ToolChoiceValue.None => "none",
                ToolChoiceValue.Required => "required",
                _ => throw new JsonException($"Unknown ToolChoiceValue: {value.Value}"),
            };
            writer.WriteStringValue(str);
        }
        else if (value.Specific != null)
        {
            JsonSerializer.Serialize(writer, value.Specific, ResponsesSerializationContext.Default.SpecificToolChoice);
        }
        else
        {
            writer.WriteNullValue();
        }
    }
}

// =====================================================================================================================
// Configuration objects
// =====================================================================================================================

public class ReasoningConfig
{
    [JsonPropertyName("effort")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Effort { get; set; }

    [JsonPropertyName("summary")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Summary { get; set; }
}

public class TextConfig
{
    [JsonPropertyName("format")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public TextFormat? Format { get; set; }

    [JsonPropertyName("verbosity")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Verbosity { get; set; }
}

public class TextFormat
{
    /// <summary>One of: text, json_object, json_schema, lark_grammar, regex.</summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = "text";

    [JsonPropertyName("name")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Name { get; set; }

    [JsonPropertyName("description")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Description { get; set; }

    [JsonPropertyName("schema")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? Schema { get; set; }

    [JsonPropertyName("strict")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Strict { get; set; }

    [JsonPropertyName("grammar")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Grammar { get; set; }
}

public class ResponseUsage
{
    [JsonPropertyName("input_tokens")]
    public int InputTokens { get; set; }

    [JsonPropertyName("output_tokens")]
    public int OutputTokens { get; set; }

    [JsonPropertyName("total_tokens")]
    public int TotalTokens { get; set; }

    [JsonPropertyName("input_tokens_details")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public InputTokensDetails? InputTokensDetails { get; set; }

    [JsonPropertyName("output_tokens_details")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public OutputTokensDetails? OutputTokensDetails { get; set; }
}

public class InputTokensDetails
{
    [JsonPropertyName("cached_tokens")]
    public int CachedTokens { get; set; }
}

public class OutputTokensDetails
{
    [JsonPropertyName("reasoning_tokens")]
    public int ReasoningTokens { get; set; }
}

public class ResponseError
{
    [JsonPropertyName("code")]
    public required string Code { get; set; }

    [JsonPropertyName("message")]
    public required string Message { get; set; }
}

public class IncompleteDetails
{
    [JsonPropertyName("reason")]
    public required string Reason { get; set; }
}

// =====================================================================================================================
// Request & Response objects
// =====================================================================================================================

/// <summary>Request body for POST /v1/responses.</summary>
public class ResponseCreateRequest
{
    [JsonPropertyName("model")]
    public required string Model { get; set; }

    [JsonPropertyName("input")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ResponseInput? Input { get; set; }

    [JsonPropertyName("instructions")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Instructions { get; set; }

    [JsonPropertyName("previous_response_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? PreviousResponseId { get; set; }

    [JsonPropertyName("tools")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<FunctionToolDefinition>? Tools { get; set; }

    [JsonPropertyName("tool_choice")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ToolChoice? ToolChoice { get; set; }

    [JsonPropertyName("temperature")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public float? Temperature { get; set; }

    [JsonPropertyName("top_p")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public float? TopP { get; set; }

    [JsonPropertyName("presence_penalty")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public float? PresencePenalty { get; set; }

    [JsonPropertyName("frequency_penalty")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public float? FrequencyPenalty { get; set; }

    [JsonPropertyName("max_output_tokens")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? MaxOutputTokens { get; set; }

    [JsonPropertyName("parallel_tool_calls")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? ParallelToolCalls { get; set; }

    [JsonPropertyName("truncation")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public TruncationValue? Truncation { get; set; }

    [JsonPropertyName("store")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Store { get; set; }

    [JsonPropertyName("metadata")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Dictionary<string, string>? Metadata { get; set; }

    [JsonPropertyName("stream")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Stream { get; set; }

    [JsonPropertyName("reasoning")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ReasoningConfig? Reasoning { get; set; }

    [JsonPropertyName("text")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public TextConfig? Text { get; set; }

    [JsonPropertyName("seed")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? Seed { get; set; }

    [JsonPropertyName("user")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? User { get; set; }
}

/// <summary>The Response resource returned by the Responses API.</summary>
public class ResponseObject
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    [JsonPropertyName("object")]
    public string ObjectType { get; set; } = "response";

    [JsonPropertyName("created_at")]
    public long CreatedAt { get; set; }

    [JsonPropertyName("completed_at")]
    public long? CompletedAt { get; set; }

    [JsonPropertyName("failed_at")]
    public long? FailedAt { get; set; }

    [JsonPropertyName("cancelled_at")]
    public long? CancelledAt { get; set; }

    [JsonPropertyName("status")]
    public ResponseStatus Status { get; set; }

    [JsonPropertyName("incomplete_details")]
    public IncompleteDetails? IncompleteDetails { get; set; }

    [JsonPropertyName("model")]
    public string Model { get; set; } = string.Empty;

    [JsonPropertyName("previous_response_id")]
    public string? PreviousResponseId { get; set; }

    [JsonPropertyName("instructions")]
    public string? Instructions { get; set; }

    [JsonPropertyName("output")]
    public List<ResponseItem> Output { get; set; } = [];

    [JsonPropertyName("error")]
    public ResponseError? Error { get; set; }

    [JsonPropertyName("tools")]
    public List<FunctionToolDefinition> Tools { get; set; } = [];

    [JsonPropertyName("tool_choice")]
    public ToolChoice? ToolChoice { get; set; }

    [JsonPropertyName("truncation")]
    public TruncationValue? Truncation { get; set; }

    [JsonPropertyName("parallel_tool_calls")]
    public bool ParallelToolCalls { get; set; }

    [JsonPropertyName("text")]
    public TextConfig? Text { get; set; }

    [JsonPropertyName("top_p")]
    public float? TopP { get; set; }

    [JsonPropertyName("presence_penalty")]
    public float? PresencePenalty { get; set; }

    [JsonPropertyName("frequency_penalty")]
    public float? FrequencyPenalty { get; set; }

    [JsonPropertyName("temperature")]
    public float? Temperature { get; set; }

    [JsonPropertyName("reasoning")]
    public ReasoningConfig? Reasoning { get; set; }

    [JsonPropertyName("usage")]
    public ResponseUsage? Usage { get; set; }

    [JsonPropertyName("max_output_tokens")]
    public int? MaxOutputTokens { get; set; }

    [JsonPropertyName("store")]
    public bool Store { get; set; }

    [JsonPropertyName("metadata")]
    public Dictionary<string, string>? Metadata { get; set; }

    [JsonPropertyName("user")]
    public string? User { get; set; }

    /// <summary>
    /// Convenience: concatenates text from assistant <see cref="MessageItem"/> instances in <see cref="Output"/>.
    /// Returns empty string if no assistant message is found.
    /// </summary>
    [JsonIgnore]
    public string OutputText
    {
        get
        {
            var sb = new System.Text.StringBuilder();
            foreach (var item in Output)
            {
                if (item is MessageItem msg && msg.Role == MessageRole.Assistant)
                {
                    sb.Append(msg.Content.GetText());
                }
            }

            return sb.ToString();
        }
    }
}

// =====================================================================================================================
// Listing/Delete results
// =====================================================================================================================

public class DeleteResponseResult
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    [JsonPropertyName("object")]
    public string ObjectType { get; set; } = "response";

    [JsonPropertyName("deleted")]
    public bool Deleted { get; set; }
}

public class InputItemsListResponse
{
    [JsonPropertyName("object")]
    public string ObjectType { get; set; } = "list";

    [JsonPropertyName("data")]
    public List<ResponseItem> Data { get; set; } = [];

    [JsonPropertyName("first_id")]
    public string? FirstId { get; set; }

    [JsonPropertyName("last_id")]
    public string? LastId { get; set; }

    [JsonPropertyName("has_more")]
    public bool HasMore { get; set; }
}

public class ListResponsesResult
{
    [JsonPropertyName("object")]
    public string ObjectType { get; set; } = "list";

    [JsonPropertyName("data")]
    public List<ResponseObject> Data { get; set; } = [];

    [JsonPropertyName("first_id")]
    public string? FirstId { get; set; }

    [JsonPropertyName("last_id")]
    public string? LastId { get; set; }

    [JsonPropertyName("has_more")]
    public bool HasMore { get; set; }
}

// =====================================================================================================================
// Streaming Events (polymorphic)
// =====================================================================================================================

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(ResponseCreatedEvent), "response.created")]
[JsonDerivedType(typeof(ResponseQueuedEvent), "response.queued")]
[JsonDerivedType(typeof(ResponseInProgressEvent), "response.in_progress")]
[JsonDerivedType(typeof(ResponseCompletedEvent), "response.completed")]
[JsonDerivedType(typeof(ResponseFailedEvent), "response.failed")]
[JsonDerivedType(typeof(ResponseIncompleteEvent), "response.incomplete")]
[JsonDerivedType(typeof(OutputItemAddedEvent), "response.output_item.added")]
[JsonDerivedType(typeof(OutputItemDoneEvent), "response.output_item.done")]
[JsonDerivedType(typeof(ReasoningSummaryPartAddedEvent), "response.reasoning_summary_part.added")]
[JsonDerivedType(typeof(ReasoningSummaryPartDoneEvent), "response.reasoning_summary_part.done")]
[JsonDerivedType(typeof(ContentPartAddedEvent), "response.content_part.added")]
[JsonDerivedType(typeof(ContentPartDoneEvent), "response.content_part.done")]
[JsonDerivedType(typeof(OutputTextDeltaEvent), "response.output_text.delta")]
[JsonDerivedType(typeof(OutputTextDoneEvent), "response.output_text.done")]
[JsonDerivedType(typeof(RefusalDeltaEvent), "response.refusal.delta")]
[JsonDerivedType(typeof(RefusalDoneEvent), "response.refusal.done")]
[JsonDerivedType(typeof(ReasoningDeltaEvent), "response.reasoning.delta")]
[JsonDerivedType(typeof(ReasoningDoneEvent), "response.reasoning.done")]
[JsonDerivedType(typeof(ReasoningSummaryDeltaEvent), "response.reasoning_summary_text.delta")]
[JsonDerivedType(typeof(ReasoningSummaryDoneEvent), "response.reasoning_summary_text.done")]
[JsonDerivedType(typeof(OutputTextAnnotationAddedEvent), "response.output_text.annotation.added")]
[JsonDerivedType(typeof(FunctionCallArgumentsDeltaEvent), "response.function_call_arguments.delta")]
[JsonDerivedType(typeof(FunctionCallArgumentsDoneEvent), "response.function_call_arguments.done")]
[JsonDerivedType(typeof(ErrorEvent), "error")]
public abstract class StreamingEvent
{
    /// <summary>The event type discriminator (e.g. "response.created").</summary>
    [JsonIgnore]
    public abstract string EventType { get; }

    [JsonPropertyName("sequence_number")]
    public int SequenceNumber { get; set; }
}

public sealed class ResponseCreatedEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.created";
    [JsonPropertyName("response")] public required ResponseObject Response { get; set; }
}

public sealed class ResponseQueuedEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.queued";
    [JsonPropertyName("response")] public required ResponseObject Response { get; set; }
}

public sealed class ResponseInProgressEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.in_progress";
    [JsonPropertyName("response")] public required ResponseObject Response { get; set; }
}

public sealed class ResponseCompletedEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.completed";
    [JsonPropertyName("response")] public required ResponseObject Response { get; set; }
}

public sealed class ResponseFailedEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.failed";
    [JsonPropertyName("response")] public required ResponseObject Response { get; set; }
}

public sealed class ResponseIncompleteEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.incomplete";
    [JsonPropertyName("response")] public required ResponseObject Response { get; set; }
}

public sealed class OutputItemAddedEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.output_item.added";
    [JsonPropertyName("item_id")] public required string ItemId { get; set; }
    [JsonPropertyName("output_index")] public int OutputIndex { get; set; }
    [JsonPropertyName("item")] public required ResponseItem Item { get; set; }
}

public sealed class OutputItemDoneEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.output_item.done";
    [JsonPropertyName("item_id")] public required string ItemId { get; set; }
    [JsonPropertyName("output_index")] public int OutputIndex { get; set; }
    [JsonPropertyName("item")] public required ResponseItem Item { get; set; }
}

public sealed class ContentPartAddedEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.content_part.added";
    [JsonPropertyName("item_id")] public required string ItemId { get; set; }
    [JsonPropertyName("output_index")] public int OutputIndex { get; set; }
    [JsonPropertyName("content_index")] public int ContentIndex { get; set; }
    [JsonPropertyName("part")] public required ContentPart Part { get; set; }
}

public sealed class ContentPartDoneEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.content_part.done";
    [JsonPropertyName("item_id")] public required string ItemId { get; set; }
    [JsonPropertyName("output_index")] public int OutputIndex { get; set; }
    [JsonPropertyName("content_index")] public int ContentIndex { get; set; }
    [JsonPropertyName("part")] public required ContentPart Part { get; set; }
}

public sealed class OutputTextDeltaEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.output_text.delta";
    [JsonPropertyName("item_id")] public required string ItemId { get; set; }
    [JsonPropertyName("output_index")] public int OutputIndex { get; set; }
    [JsonPropertyName("content_index")] public int ContentIndex { get; set; }
    [JsonPropertyName("delta")] public required string Delta { get; set; }
}

public sealed class OutputTextDoneEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.output_text.done";
    [JsonPropertyName("item_id")] public required string ItemId { get; set; }
    [JsonPropertyName("output_index")] public int OutputIndex { get; set; }
    [JsonPropertyName("content_index")] public int ContentIndex { get; set; }
    [JsonPropertyName("text")] public required string Text { get; set; }
}

public sealed class RefusalDeltaEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.refusal.delta";
    [JsonPropertyName("item_id")] public required string ItemId { get; set; }
    [JsonPropertyName("output_index")] public int OutputIndex { get; set; }
    [JsonPropertyName("content_index")] public int ContentIndex { get; set; }
    [JsonPropertyName("delta")] public required string Delta { get; set; }
}

public sealed class RefusalDoneEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.refusal.done";
    [JsonPropertyName("item_id")] public required string ItemId { get; set; }
    [JsonPropertyName("output_index")] public int OutputIndex { get; set; }
    [JsonPropertyName("content_index")] public int ContentIndex { get; set; }
    [JsonPropertyName("refusal")] public required string Refusal { get; set; }
}

public sealed class FunctionCallArgumentsDeltaEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.function_call_arguments.delta";
    [JsonPropertyName("item_id")] public required string ItemId { get; set; }
    [JsonPropertyName("output_index")] public int OutputIndex { get; set; }
    [JsonPropertyName("call_id")] public string? CallId { get; set; }
    [JsonPropertyName("delta")] public required string Delta { get; set; }
}

public sealed class FunctionCallArgumentsDoneEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.function_call_arguments.done";
    [JsonPropertyName("item_id")] public required string ItemId { get; set; }
    [JsonPropertyName("output_index")] public int OutputIndex { get; set; }
    [JsonPropertyName("call_id")] public string? CallId { get; set; }
    [JsonPropertyName("arguments")] public required string Arguments { get; set; }
    [JsonPropertyName("name")] public string? Name { get; set; }
}

public sealed class ReasoningSummaryPartAddedEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.reasoning_summary_part.added";
    [JsonPropertyName("item_id")] public required string ItemId { get; set; }
    [JsonPropertyName("output_index")] public int OutputIndex { get; set; }
    [JsonPropertyName("summary_index")] public int SummaryIndex { get; set; }
    [JsonPropertyName("part")] public required ContentPart Part { get; set; }
}

public sealed class ReasoningSummaryPartDoneEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.reasoning_summary_part.done";
    [JsonPropertyName("item_id")] public required string ItemId { get; set; }
    [JsonPropertyName("output_index")] public int OutputIndex { get; set; }
    [JsonPropertyName("summary_index")] public int SummaryIndex { get; set; }
    [JsonPropertyName("part")] public required ContentPart Part { get; set; }
}

public sealed class ReasoningDeltaEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.reasoning.delta";
    [JsonPropertyName("item_id")] public required string ItemId { get; set; }
    [JsonPropertyName("output_index")] public int OutputIndex { get; set; }
    [JsonPropertyName("content_index")] public int ContentIndex { get; set; }
    [JsonPropertyName("delta")] public required string Delta { get; set; }
}

public sealed class ReasoningDoneEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.reasoning.done";
    [JsonPropertyName("item_id")] public required string ItemId { get; set; }
    [JsonPropertyName("output_index")] public int OutputIndex { get; set; }
    [JsonPropertyName("content_index")] public int ContentIndex { get; set; }
    [JsonPropertyName("text")] public required string Text { get; set; }
}

public sealed class ReasoningSummaryDeltaEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.reasoning_summary_text.delta";
    [JsonPropertyName("item_id")] public required string ItemId { get; set; }
    [JsonPropertyName("output_index")] public int OutputIndex { get; set; }
    [JsonPropertyName("summary_index")] public int SummaryIndex { get; set; }
    [JsonPropertyName("delta")] public required string Delta { get; set; }
}

public sealed class ReasoningSummaryDoneEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.reasoning_summary_text.done";
    [JsonPropertyName("item_id")] public required string ItemId { get; set; }
    [JsonPropertyName("output_index")] public int OutputIndex { get; set; }
    [JsonPropertyName("summary_index")] public int SummaryIndex { get; set; }
    [JsonPropertyName("text")] public required string Text { get; set; }
}

public sealed class OutputTextAnnotationAddedEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "response.output_text.annotation.added";
    [JsonPropertyName("item_id")] public required string ItemId { get; set; }
    [JsonPropertyName("output_index")] public int OutputIndex { get; set; }
    [JsonPropertyName("content_index")] public int ContentIndex { get; set; }
    [JsonPropertyName("annotation_index")] public int AnnotationIndex { get; set; }
    [JsonPropertyName("annotation")] public Annotation? Annotation { get; set; }
}

public sealed class ErrorEvent : StreamingEvent
{
    [JsonIgnore] public override string EventType => "error";

    [JsonPropertyName("code")] public string? Code { get; set; }
    [JsonPropertyName("message")] public string? Message { get; set; }
    [JsonPropertyName("param")] public string? Param { get; set; }
}

// =====================================================================================================================
// API error envelope
// =====================================================================================================================

public class ApiErrorDetail
{
    [JsonPropertyName("message")]
    public string? Message { get; set; }

    [JsonPropertyName("type")]
    public string? Type { get; set; }

    [JsonPropertyName("param")]
    public string? Param { get; set; }

    [JsonPropertyName("code")]
    public string? Code { get; set; }
}

public class ApiErrorResponse
{
    [JsonPropertyName("error")]
    public ApiErrorDetail? Error { get; set; }
}
