// <complete_code>
// <imports>
using Microsoft.AI.Foundry.Local;
using System.Text.Json;
// </imports>

// <init>
CancellationToken ct = new CancellationToken();

var config = new Configuration
{
    AppName = "foundry_local_samples",
    LogLevel = Microsoft.AI.Foundry.Local.LogLevel.Information
};


// Initialize the singleton instance.
await FoundryLocalManager.CreateAsync(config, Utils.GetAppLogger());
var mgr = FoundryLocalManager.Instance;


// Ensure that any Execution Provider (EP) downloads run and are completed.
// Download and register all execution providers.
var currentEp = "";
await mgr.DownloadAndRegisterEpsAsync((epName, percent) =>
{
    if (epName != currentEp)
    {
        if (currentEp != "") Console.WriteLine();
        currentEp = epName;
    }
    Console.Write($"\r  {epName.PadRight(30)}  {percent,6:F1}%");
});
if (currentEp != "") Console.WriteLine();
// </init>


// <model_setup>
// Get the model catalog
var catalog = await mgr.GetCatalogAsync();


// Get a model using an alias.
var model = await catalog.GetModelAsync("qwen2.5-0.5b") ?? throw new Exception("Model not found");


// Download the model (the method skips download if already cached)
await model.DownloadAsync(progress =>
{
    Console.Write($"\rDownloading model: {progress:F2}%");
    if (progress >= 100f)
    {
        Console.WriteLine();
    }
});


// Load the model
Console.Write($"Loading model {model.Id}...");
await model.LoadAsync();
Console.WriteLine("done.");
// </model_setup>


// Create a chat session and register the tool definition.
// AddToolDefinition makes the tool visible to the model for every request on this session.
using var session = new ChatSession(model);


// <tool_definitions>
session.AddToolDefinition(
    "multiply_numbers",
    "A tool for multiplying two numbers.",
    /*lang=json,strict*/
    """
    {
      "type": "object",
      "properties": {
        "first": { "type": "integer", "description": "The first number in the operation" },
        "second": { "type": "integer", "description": "The second number in the operation" }
      },
      "required": ["first", "second"]
    }
    """);
// </tool_definitions>


// <tool_loop>
// Turn 1: force a tool call so we can demonstrate the tool-result round-trip.
// ChatSession accumulates message history, so we only add new items each turn.
using (var request = new Request())
{
    request.AddItem(MessageItem.System(
        "You are a helpful AI assistant. If necessary, you can use any provided tools to answer the question."));
    request.AddItem(MessageItem.User("What is the answer to 7 multiplied by 6?"));
    request.SetOptions(new RequestOptions { ToolChoice = ToolChoice.Required });

    Console.WriteLine("Chat completion response:");
    using var response = await session.ProcessRequestAsync(request, ct);

    // Collect tool calls from the response, then invoke them and feed results back as a second request.
    // The response is iterated in order; each item must be disposed once we are done with it.
    var pendingResults = new List<ToolResultItem>();
    foreach (var item in response)
    {
        using (item)
        {
            if (item is ToolCallItem call && call.Name == "multiply_numbers")
            {
                var arguments = JsonSerializer.Deserialize<Dictionary<string, int>>(call.Arguments)!;
                var first = arguments["first"];
                var second = arguments["second"];

                Console.WriteLine($"\nInvoking tool: {call.Name} with arguments {first} and {second}");
                var result = Utils.MultiplyNumbers(first, second);
                Console.WriteLine($"Tool response: {result}");

                pendingResults.Add(new ToolResultItem(call.CallId, result.ToString()));
            }
        }
    }

    Console.WriteLine("\nTool calls completed. Prompting model to continue conversation...\n");

    // Turn 2: send the tool results back. ToolChoice defaults to Auto so the model can either
    // call the tool again or answer the user directly.
    using var followUp = new Request();
    foreach (var toolResult in pendingResults)
    {
        followUp.AddItem(toolResult);
    }
    followUp.AddItem(MessageItem.System("Respond only with the answer generated by the tool."));

    session.SetStreaming(true);
    Console.WriteLine("Chat completion response:");
    await foreach (var item in session.ProcessStreamingRequestAsync(followUp, ct))
    {
        using (item)
        {
            if (item is TextItem txt)
            {
                Console.Write(txt.Text);
                Console.Out.Flush();
            }
        }
    }
    Console.WriteLine();
}
// </tool_loop>


// <cleanup>
// Tidy up - unload the model and dispose the manager so native resources are released promptly.
session.Dispose();
await model.UnloadAsync();
mgr.Dispose();
// </cleanup>
// </complete_code>