// <complete_code>
// <imports>
import { ChatSession, FoundryLocalManager, Item, Request } from 'foundry-local-sdk';
// </imports>

// <tool_definitions>
function multiplyNumbers(first, second) {
    return first * second;
}

const MULTIPLY_NUMBERS_SCHEMA = JSON.stringify({
    type: 'object',
    properties: {
        first: { type: 'integer', description: 'The first number in the operation' },
        second: { type: 'integer', description: 'The second number in the operation' }
    },
    required: ['first', 'second']
});
// </tool_definitions>

// <init>
const manager = FoundryLocalManager.create({
    appName: 'foundry_local_samples',
    logLevel: 'info'
});
// </init>

// Download and register all execution providers.
let currentEp = '';
await manager.downloadAndRegisterEps((epName, percent) => {
    if (epName !== currentEp) {
        if (currentEp !== '') process.stdout.write('\n');
        currentEp = epName;
    }
    process.stdout.write(`\r  ${epName.padEnd(30)}  ${percent.toFixed(1).padStart(5)}%`);
});
if (currentEp !== '') process.stdout.write('\n');

// <model_setup>
const modelAlias = 'qwen2.5-0.5b';
const model = await manager.catalog.getModel(modelAlias);

console.log(`\nDownloading model ${modelAlias}...`);
await model.download((progress) => {
    process.stdout.write(`\rDownloading... ${progress.toFixed(2)}%`);
});
console.log('\n✓ Model downloaded');

console.log(`Loading model ${modelAlias}...`);
await model.load();
console.log('✓ Model loaded');
// </model_setup>

// <tool_loop>
// Register the tool definition on the session. The model sees it on every turn.
const session = new ChatSession(model);
try {
    session.addToolDefinition({
        name: 'multiply_numbers',
        description: 'A tool for multiplying two numbers.',
        jsonSchema: MULTIPLY_NUMBERS_SCHEMA
    });

    // Turn 1: force a tool call so we can demonstrate the round-trip.
    // ChatSession accumulates message history, so we only add new items each turn.
    const req1 = new Request();
    req1.addItem(Item.systemMessage(
        'You are a helpful AI assistant. If necessary, you can use any provided tools to answer the question.'
    ));
    req1.addItem(Item.userMessage('What is the answer to 7 multiplied by 6?'));
    req1.setOptions({ toolChoice: 'required' });

    console.log('\nChat completion response:');
    const response = await session.processRequest(req1);

    // Collect tool calls, invoke them, and prepare the tool-result items for turn 2.
    const pendingResults = [];
    for (const item of response.output) {
        if (item.type === 'toolCall' && item.name === 'multiply_numbers') {
            const args = JSON.parse(item.arguments);
            console.log(`\nInvoking tool: ${item.name} with arguments ${args.first} and ${args.second}`);
            const result = multiplyNumbers(args.first, args.second);
            console.log(`Tool response: ${result}`);
            pendingResults.push(Item.toolResult(item.callId, result.toString()));
        }
    }

    console.log('\nTool calls completed. Prompting model to continue conversation...\n');

    // Turn 2: send the tool results back. toolChoice defaults to 'auto'.
    const req2 = new Request();
    for (const toolResult of pendingResults) {
        req2.addItem(toolResult);
    }
    req2.addItem(Item.systemMessage('Respond only with the answer generated by the tool.'));

    console.log('Chat completion response:');
    for await (const item of session.processStreamingRequest(req2)) {
        if (item.type === 'text') {
            process.stdout.write(item.text);
        }
    }
    process.stdout.write('\n');
} finally {
    session.dispose();
}
// </tool_loop>

// <cleanup>
console.log('Unloading model...');
await model.unload();
console.log('✓ Model unloaded');
// </cleanup>
// </complete_code>
