[source.crates-io]
replace-with = "AIFoundryLocal_PublicPackages"

[source.AIFoundryLocal_PublicPackages]
registry = "sparse+https://pkgs.dev.azure.com/aiinfra/AIFoundryLocal/_packaging/AIFoundryLocal_PublicPackages/Cargo/index/"

[registries]
AIFoundryLocal_PublicPackages = { index = "sparse+https://pkgs.dev.azure.com/aiinfra/AIFoundryLocal/_packaging/AIFoundryLocal_PublicPackages/Cargo/index/" }

[registry]
global-credential-providers = ["cargo:token"]
