// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
//
// catalog_snapshot — fetches the live Azure model catalog and emits a
// catalog_snapshot_data.cc file ready to drop into src/catalog/.
//
// This is a build-time tool, not part of the SDK runtime. It reaches into
// internal SDK symbols (MakeCatalogClient, ModelInfoToJson, IEpDetector)
// rather than the public C++ wrapper.

#include "catalog/catalog_client.h"
#include "ep_detection/ep_detector.h"
#include "logger.h"
#include "model_info.h"

#include <nlohmann/json.hpp>

#include <chrono>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <exception>
#include <fstream>
#include <iostream>
#include <map>
#include <string>
#include <string_view>
#include <vector>

namespace {

// Default Azure catalog endpoint. Mirrors kDefaultCatalogUrl in
// AzureModelCatalog. Duplicating one URL string is acceptable for a
// throwaway tool — keeping a shared constant would require exposing a
// new header.
constexpr const char* kDefaultCatalogUrl = "https://ai.azure.com/api/eastus/ux/v1.0";

// Snapshot envelope version. Must match CatalogCache::kCacheVersion and the
// kSnapshotVersion constant in catalog_cache.cc. Hard-coded here because
// neither constant is exposed in a public header.
constexpr int kSnapshotVersion = 1;

/// Pretends every (device, EP) combination we want to ship is available, so
/// the catalog returns the union of all variants for every supported runtime.
class AllEpsDetector : public fl::IEpDetector {
 public:
  std::map<std::string, std::vector<std::string>> GetAvailableDevicesToEPs() const override {
    return {
        {"CPU", {"CPUExecutionProvider", "OpenVINOExecutionProvider"}},
        {"GPU", {"DmlExecutionProvider", "CUDAExecutionProvider", "NvTensorRTRTXExecutionProvider", "OpenVINOExecutionProvider", "QNNExecutionProvider", "VitisAIExecutionProvider", "WebGpuExecutionProvider"}},
        {"NPU", {"OpenVINOExecutionProvider", "QNNExecutionProvider", "VitisAIExecutionProvider"}},
    };
  }
};

void PrintUsage() {
  std::cerr << "Usage: catalog_snapshot --output <path/to/catalog_snapshot_data.cc>\n"
               "                        [--filter <filter_string>]\n"
               "                        [--url <catalog_url>]\n"
               "\n"
               "  --output  REQUIRED. Path to the .cc file to write.\n"
               "  --filter  Catalog filter. Defaults to empty (public-only models).\n"
               "  --url     Catalog endpoint. Defaults to the Azure eastus catalog.\n";
}

struct Args {
  std::string output;
  std::string filter;
  std::string url = kDefaultCatalogUrl;
};

/// Returns false on parse error; prints usage to stderr in that case.
bool ParseArgs(int argc, char** argv, Args& out) {
  for (int i = 1; i < argc; ++i) {
    std::string_view a = argv[i];

    auto take_value = [&](std::string& dest) -> bool {
      if (i + 1 >= argc) {
        std::cerr << "error: missing value for " << a << "\n";
        return false;
      }
      dest = argv[++i];
      return true;
    };

    if (a == "--output") {
      if (!take_value(out.output)) {
        return false;
      }
    } else if (a == "--filter") {
      if (!take_value(out.filter)) {
        return false;
      }
    } else if (a == "--url") {
      if (!take_value(out.url)) {
        return false;
      }
    } else if (a == "--help" || a == "-h") {
      PrintUsage();
      return false;
    } else {
      std::cerr << "error: unknown argument: " << a << "\n";
      return false;
    }
  }

  if (out.output.empty()) {
    std::cerr << "error: --output is required\n";
    return false;
  }

  return true;
}

/// Writes `bytes` as a C array literal, 16 bytes per line, lowercase hex
/// (xxd convention). No null terminator — the byte count is the size.
void WriteByteArray(std::ostream& os, const std::string& bytes) {
  constexpr std::size_t kPerLine = 16;
  char buf[8];

  for (std::size_t i = 0; i < bytes.size(); ++i) {
    if (i % kPerLine == 0) {
      os << "    ";
    }

    std::snprintf(buf, sizeof(buf), "0x%02x,", static_cast<unsigned>(static_cast<unsigned char>(bytes[i])));
    os << buf;

    if (i + 1 == bytes.size() || (i + 1) % kPerLine == 0) {
      os << "\n";
    } else {
      os << " ";
    }
  }
}

void WriteSnapshotFile(const std::string& path,
                       const std::string& json,
                       const Args& args,
                       std::size_t model_count) {
  std::ofstream out(path, std::ios::binary | std::ios::trunc);
  if (!out) {
    throw std::runtime_error("failed to open output file: " + path);
  }

  out << "// Copyright (c) Microsoft Corporation. All rights reserved.\n"
      << "// Licensed under the MIT License.\n"
      << "//\n"
      << "// GENERATED FILE \xE2\x80\x94 DO NOT EDIT BY HAND.\n"
      << "// Generated by tools/catalog_snapshot.\n"
      << "//   filter: " << args.filter << "\n"
      << "//   url:    " << args.url << "\n"
      << "//   models: " << model_count << "\n"
      << "#include \"catalog/catalog_snapshot_data.h\"\n"
      << "\n"
      << "namespace fl {\n"
      << "\n"
      << "const unsigned char kCatalogSnapshotJson[] = {\n";

  WriteByteArray(out, json);

  out << "};\n"
      << "\n"
      << "const std::size_t kCatalogSnapshotJsonSize = sizeof(kCatalogSnapshotJson);\n"
      << "\n"
      << "}  // namespace fl\n";

  if (!out) {
    throw std::runtime_error("failed while writing output file: " + path);
  }
}

}  // namespace

int main(int argc, char** argv) {
  Args args;
  if (!ParseArgs(argc, argv, args)) {
    PrintUsage();
    return 1;
  }

  try {
    fl::StderrLogger logger;
    AllEpsDetector ep_detector;

    // Empty cache_directory disables the on-disk cache write-through;
    // we only want the in-memory model list to serialize.
    auto client = fl::MakeCatalogClient(args.url, args.filter, ep_detector, logger,
                                        /*cache_directory=*/"");

    const auto model_infos = fl::FetchAllModelInfosWithCachedModels(*client, /*cached_model_ids=*/{}, logger);

    nlohmann::json root;
    root["version"] = kSnapshotVersion;
    root["savedAtUnix"] = std::chrono::duration_cast<std::chrono::seconds>(
                              std::chrono::system_clock::now().time_since_epoch())
                              .count();

    nlohmann::json models = nlohmann::json::array();
    for (const auto& info : model_infos) {
      models.push_back(fl::ModelInfoToJson(info));
    }
    root["models"] = std::move(models);

    // Compact dump — no pretty-printing — to minimize the embedded size.
    const std::string json_str = root.dump();

    WriteSnapshotFile(args.output, json_str, args, model_infos.size());

    std::cerr << "wrote " << model_infos.size() << " models to " << args.output
              << " (" << json_str.size() << " bytes)\n";
    return 0;
  } catch (const std::exception& ex) {
    std::cerr << "catalog_snapshot failed: " << ex.what() << "\n";
    return 2;
  }
}
