// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
//
// The raw-envelope descriptor: how a turn declares that one of its custom tools is written straight into visible
// output, and what makes such a declaration valid.
//
// A descriptor decides whether a run of generated bytes is a tool call or a paragraph, so an invalid one is never
// guessed at or half-applied. These tests pin down the validation rules, the request-over-model resolution order,
// and the fact that a change of dialect is a change of session identity.
//
#include "inferencing/generative/toolcalling/raw_envelope_encoding.h"

#include "exception.h"
#include "inferencing/generative/toolcalling/tool_call_context.h"

#include <gtest/gtest.h>
#include <nlohmann/json.hpp>

#include <string>

using namespace fl;

namespace {

/// A well-formed descriptor, as a request option or model property would carry it.
std::string ValidJson(const std::string& tool = "apply_patch", const std::string& begin = "*** Begin Patch",
                      const std::string& end = "*** End Patch") {
  nlohmann::json j{{"type", "raw_envelope"}, {"tool_name", tool}, {"start_marker", begin}, {"end_marker", end}};
  return j.dump();
}

/// Assert that a configured value is rejected, and that the reported error is a caller error rather than a crash or
/// an internal fault — a bad descriptor is something the caller can fix.
void ExpectRejected(const std::string& text, const char* why) {
  SCOPED_TRACE(why);

  try {
    ParseToolOutputEncoding(text, "request option");
    ADD_FAILURE() << "expected rejection: " << why;
  } catch (const fl::Exception& e) {
    EXPECT_EQ(e.code(), FOUNDRY_LOCAL_ERROR_INVALID_ARGUMENT);
  }
}

}  // namespace

// ==========================================================================
// Shape and validation.
// ==========================================================================

TEST(RawEnvelopeEncodingTest, ValidDescriptorParsesEveryField) {
  const auto encoding = ParseToolOutputEncoding(ValidJson(), "request option");

  ASSERT_TRUE(encoding.has_value());
  EXPECT_EQ(encoding->tool_name, "apply_patch");
  EXPECT_EQ(encoding->start_marker, "*** Begin Patch");
  EXPECT_EQ(encoding->end_marker, "*** End Patch");
}

TEST(RawEnvelopeEncodingTest, ArbitraryToolAndMarkersAreAccepted) {
  // Nothing about apply_patch is privileged; the descriptor is data.
  const auto encoding = ParseToolOutputEncoding(ValidJson("edit_file", "<<<EDIT", "EDIT>>>"), "request option");

  ASSERT_TRUE(encoding.has_value());
  EXPECT_EQ(encoding->tool_name, "edit_file");
  EXPECT_EQ(encoding->start_marker, "<<<EDIT");
  EXPECT_EQ(encoding->end_marker, "EDIT>>>");
}

TEST(RawEnvelopeEncodingTest, RoundTripsThroughJsonExactly) {
  const auto original = ParseToolOutputEncoding(ValidJson("edit_file", "@@B@@", "@@E@@"), "request option");
  ASSERT_TRUE(original.has_value());

  const nlohmann::json serialized = *original;
  const auto restored = serialized.get<RawEnvelopeEncoding>();

  EXPECT_EQ(restored, *original) << "a stored descriptor must come back byte-for-byte identical";
  EXPECT_EQ(serialized.at("type"), "raw_envelope");
}

TEST(RawEnvelopeEncodingTest, BlankValueMeansNotConfigured) {
  EXPECT_FALSE(ParseToolOutputEncoding("", "request option").has_value());
  EXPECT_FALSE(ParseToolOutputEncoding("   \t\n ", "request option").has_value());
}

TEST(RawEnvelopeEncodingTest, MalformedAndWronglyTypedValuesAreRejected) {
  ExpectRejected("{not json", "not JSON at all");
  ExpectRejected("\"raw_envelope\"", "a bare string, not an object");
  ExpectRejected("[]", "an array, not an object");
  ExpectRejected("123", "a number, not an object");
  ExpectRejected(R"({"tool_name":"t","start_marker":"a","end_marker":"b"})", "no type");
  ExpectRejected(R"({"type":"structured","tool_name":"t","start_marker":"a","end_marker":"b"})", "unknown type");
  ExpectRejected(R"({"type":7,"tool_name":"t","start_marker":"a","end_marker":"b"})", "non-string type");
}

TEST(RawEnvelopeEncodingTest, MissingEmptyAndNonStringFieldsAreRejected) {
  ExpectRejected(R"({"type":"raw_envelope","start_marker":"a","end_marker":"b"})", "no tool_name");
  ExpectRejected(R"({"type":"raw_envelope","tool_name":"t","end_marker":"b"})", "no start_marker");
  ExpectRejected(R"({"type":"raw_envelope","tool_name":"t","start_marker":"a"})", "no end_marker");
  ExpectRejected(ValidJson("", "a", "b"), "empty tool_name");
  ExpectRejected(ValidJson("t", "", "b"), "empty start_marker");
  ExpectRejected(ValidJson("t", "a", ""), "empty end_marker");
  ExpectRejected(R"({"type":"raw_envelope","tool_name":5,"start_marker":"a","end_marker":"b"})", "non-string name");
  ExpectRejected(R"({"type":"raw_envelope","tool_name":"t","start_marker":["a"],"end_marker":"b"})", "array marker");
}

TEST(RawEnvelopeEncodingTest, IdenticalMarkersAreRejected) {
  // An envelope whose opening line is also its closing line has no body and no way to terminate.
  ExpectRejected(ValidJson("t", "SAME", "SAME"), "start_marker equals end_marker");
}

TEST(RawEnvelopeEncodingTest, MarkersCarryingNewlinesAreRejected) {
  // Markers are matched as whole lines, so one containing a line break could never be found.
  ExpectRejected(ValidJson("t", "a\nb", "c"), "LF in start_marker");
  ExpectRejected(ValidJson("t", "a", "c\nd"), "LF in end_marker");
  ExpectRejected(ValidJson("t", "a\r", "c"), "CR in start_marker");
  ExpectRejected(ValidJson("t", "a", "\rc"), "CR in end_marker");
}

TEST(RawEnvelopeEncodingTest, UnknownFieldsAreRejectedRatherThanIgnored) {
  // An unrecognized member is either a typo for a required one or a constraint this build cannot apply. Dropping it
  // silently would read the turn's output differently than the caller asked for.
  ExpectRejected(R"({"type":"raw_envelope","tool_name":"t","start_marker":"a","end_marker":"b","strict":true})",
                 "extra member");
  ExpectRejected(R"({"type":"raw_envelope","tool_nme":"t","start_marker":"a","end_marker":"b","tool_name":"t"})",
                 "misspelled member alongside the correct one");
}

TEST(RawEnvelopeEncodingTest, ErrorNamesWhereTheBadDescriptorCameFrom) {
  // The same malformed value means different things depending on whether the caller wrote it or the model shipped it.
  try {
    ParseToolOutputEncoding("{bad", "model property");
    ADD_FAILURE() << "expected rejection";
  } catch (const fl::Exception& e) {
    EXPECT_NE(std::string(e.what()).find("model property"), std::string::npos);
    EXPECT_NE(std::string(e.what()).find("tool_output_encoding"), std::string::npos);
  }

  try {
    ParseToolOutputEncoding("{bad", "request option");
    ADD_FAILURE() << "expected rejection";
  } catch (const fl::Exception& e) {
    EXPECT_NE(std::string(e.what()).find("request option"), std::string::npos);
  }
}

// ==========================================================================
// Activation gate — ToolCallContext::ActiveRawEnvelope.
// ==========================================================================

namespace {

ToolCallContext GatedTurn() {
  ToolCallContext context;
  context.tool_output = true;
  context.tool_kinds = {{"apply_patch", ToolKind::kCustom}};
  context.tool_output_encoding = RawEnvelopeEncoding{"apply_patch", "*** Begin Patch", "*** End Patch"};
  context.forced_tool = ForcedToolChoice{"apply_patch", ToolKind::kCustom};
  return context;
}

}  // namespace

TEST(RawEnvelopeActivationTest, AllConditionsTogetherActivateTheDialect) {
  const auto context = GatedTurn();
  const auto* active = context.ActiveRawEnvelope();

  ASSERT_NE(active, nullptr);
  EXPECT_EQ(active->tool_name, "apply_patch");
}

TEST(RawEnvelopeActivationTest, EachMissingConditionDisablesTheDialect) {
  {
    auto context = GatedTurn();
    context.tool_output = false;
    EXPECT_EQ(context.ActiveRawEnvelope(), nullptr) << "tool_choice: none cannot produce a call";
  }
  {
    auto context = GatedTurn();
    context.tool_output_encoding.reset();
    EXPECT_EQ(context.ActiveRawEnvelope(), nullptr) << "no dialect configured";
  }
  {
    auto context = GatedTurn();
    context.forced_tool.reset();
    EXPECT_EQ(context.ActiveRawEnvelope(), nullptr) << "auto / required-without-a-name forces nothing";
  }
  {
    auto context = GatedTurn();
    context.forced_tool = ForcedToolChoice{"apply_patch", ToolKind::kFunction};
    EXPECT_EQ(context.ActiveRawEnvelope(), nullptr) << "a forced function is not a forced custom tool";
  }
  {
    auto context = GatedTurn();
    context.forced_tool = ForcedToolChoice{"other_tool", ToolKind::kCustom};
    EXPECT_EQ(context.ActiveRawEnvelope(), nullptr) << "a different forced tool";
  }
  {
    auto context = GatedTurn();
    context.tool_kinds.clear();
    EXPECT_EQ(context.ActiveRawEnvelope(), nullptr) << "the forced tool did not survive filtering";
  }
  {
    auto context = GatedTurn();
    context.tool_kinds["apply_patch"] = ToolKind::kFunction;
    EXPECT_EQ(context.ActiveRawEnvelope(), nullptr) << "the surviving tool of that name is a function";
  }
}

// ==========================================================================
// Cache identity — a dialect change is a different conversation setup.
// ==========================================================================

TEST(RawEnvelopeActivationTest, ChangingTheDescriptorChangesToolIdentity) {
  auto original = GatedTurn();
  auto same = GatedTurn();
  EXPECT_TRUE(original.HasSameTools(same)) << "identical turns must be reusable";

  // Same tools, same rendered JSON — only the dialect differs. Reusing a warm session across this would continue a
  // conversation whose earlier turns were read, and replayed into the prompt, under different rules.
  auto different_markers = GatedTurn();
  different_markers.tool_output_encoding = RawEnvelopeEncoding{"apply_patch", "<<<EDIT", "EDIT>>>"};
  EXPECT_FALSE(original.HasSameTools(different_markers));

  auto different_tool = GatedTurn();
  different_tool.tool_output_encoding = RawEnvelopeEncoding{"edit_file", "*** Begin Patch", "*** End Patch"};
  EXPECT_FALSE(original.HasSameTools(different_tool));

  auto removed = GatedTurn();
  removed.tool_output_encoding.reset();
  EXPECT_FALSE(original.HasSameTools(removed));
  EXPECT_FALSE(removed.HasSameTools(original));
}

TEST(RawEnvelopeActivationTest, ForcedChoiceAloneDoesNotChangeToolIdentity) {
  // The forced choice narrows `tools_json` already, so it is not compared again. Two turns with the same rendered
  // tools and the same dialect are the same setup.
  auto original = GatedTurn();
  auto other = GatedTurn();
  other.forced_tool.reset();

  EXPECT_TRUE(original.HasSameTools(other));
}
