name: SDK Build

on:
  pull_request:
    paths:
      - 'sdk/**'
      - '.github/workflows/**'
  push:
    paths:
      - 'sdk/**'
      - '.github/workflows/**'
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Windows build/test moved to .pipelines/foundry-local-packaging.yml and runs in ADO
  # MacOS ARM64 not supported in ADO, need to use GitHub Actions
  build-cs-macos:
    uses: ./.github/workflows/build-cs-steps.yml
    with:
      version: '0.9.0.${{ github.run_number }}'
      platform: 'macos'
    secrets: inherit
  build-js-macos:
    uses: ./.github/workflows/build-js-steps.yml
    with:
      version: '0.9.0.${{ github.run_number }}'
      platform: 'macos'
    secrets: inherit
  build-python-macos:
    uses: ./.github/workflows/build-python-steps.yml
    with:
      version: '0.9.0.${{ github.run_number }}'
      platform: 'macos'
    secrets: inherit
  build-rust-macos:
    uses: ./.github/workflows/build-rust-steps.yml
    with:
      platform: 'macos'
      run-integration-tests: true
    secrets: inherit